### ISSUE TITLE
Compatibility with Elegant Blue Theme?

### ISSUE THREAD

**Issue by masterw3x** [Finicalmist/ChangingBackground#2]
Hi,

First like to say this is a really neat plugin and thank you for putting time into making it, unfortunate I can not get it to work :(
I tried following your instructions to get the theme compatible and was unsuccessful. Could you perhaps spend a little time and check out the theme to see what the issue is?

If I have to change the main CSS, I am totally up for it. I uploaded the CSS to my personal repository and will make changes if needed.

Thanks,
Wex

**Comment by Finicalmist** [comment]
There are 3 issues in your CSS.
1. You defined :root twice
2. Changing the background-image in the canvas element does nothing for me
3. transition: [time] does nothing and breaks the theme

Fix:
1. Define every variable in one :root
```css
:root {
    --main-color: #057F95;
    --hover-color: #045B6B;
    --background-image: url(https://orig00.deviantart.net/8895/f/2016/155/7/7/neon_genesis_evangelion___asuka_sohryu_langley_by_rinjaa-da4zon1.png);
    --transition: 5s;
}
```

2. Change the background-image in .theme-dark .layer, .theme-dark .layers and remove 
`background: 0 0!important;`
3. Change `transition` to `transition-duration` and also define exact transition
```css
.theme-dark .layer,
.theme-dark .layers {
    background-image: var(--background-image) !important;
    transition: background-image 5s linear !important;
    transition-duration: var(--transition) !important;
    background-size: cover !important;
}
```
